### ISSUE TITLE
Allow "A file Icon" to show icons in sidebar

### ISSUE THREAD

**Issue by aasutossh** [eneko89/sublime-monokai-sidebar#2]
After trying this setting, the icons aren't showing up.
When I tried reverting, the background goes white and icons shows up.
I tried commenting out some lines but there is so much there.

I need to being able to see the icons with the dark settings.
Thanks.

**Comment by eneko89** [comment]
First of all, sorry. I haven't been actively developing nor supporting this since I published it, as I'm not using it anymore.

This was originally written for Sublime Text 2, and it's completely broken now in Sublime Text 3. I had some time to take a look and I just pushed a commit that partially fixes it. It still hides file and folder icons, though. To solve that, simply delete this 3 rules and they will show up, allowing you to use `A file Icon`:

```
    {
        "class": "icon_file_type",
        "content_margin": [0,0]
    },
    {
        "class": "icon_folder",
        "content_margin": [0,0]
    },
    {
        "class": "icon_folder_loading",
        "content_margin": [0,0]
    }
```

I'm not going to actively support this. If you are still interested in it, you can check the [Sublime Text 3 documentation for themes](https://www.sublimetext.com/docs/3/themes.html), or look for complete themes, there are some good ones out there.
