### ISSUE TITLE
Sublime Text 3 showing fluorescent stripes on Ubuntu

### ISSUE THREAD

**Issue by skykooler** [eneko89/sublime-monokai-sidebar#4]
This seems to introduce some graphical errors that manifest as fluorescent autumn colors at the top of the screen, as well as on folder icons. 
![autumnstripes](https://user-images.githubusercontent.com/1238417/48788950-e7fca800-ecb9-11e8-86df-872d820dc1d3.png)

**Comment by lepczynski** [comment]
I got the same result
![image](https://user-images.githubusercontent.com/23107895/65592307-9fbfad80-df8e-11e9-8a36-e9212530ea11.png)

**Comment by eneko89** [comment]
First of all, sorry. I haven't been actively developing nor supporting this since I published it, as I'm not using it anymore.

This was originally written for Sublime Text 2, and it's completely broken now in Sublime Text 3. I had some time to take a look and I saw the problem you guys are commenting about. I just pushed a commit that partially fixes it, but there are still some caveats: Sidebar folder and file icons are not showing (this was already like that, not new), the triangle icon to expand and collapse folders is dark (should be light to match the background) and footer is also not dark themed.

I'm not going to actively support this. If you are still interested in it, you can check the [Sublime Text 3 documentation for themes](https://www.sublimetext.com/docs/3/themes.html), or look for complete themes, there are some good ones out there.
